### ISSUE TITLE
ICE connection state: new -> checking -> disconnected in Docker

### ISSUE THREAD

**Issue by ioangatop** [jcrisp88/flutter-webrtc_python-aiortc-opencv#1]
Hi and thank you for open sourcing your work!

I followed the steps in `Running the server in docker`, but am still getting:
`ICE connection state: new -> checking -> disconnected in Docker`

The server is running in a remote server and I try to reach the website from my computer (so not a local camera).

Any idea what's wrong? I believe the problem is that the ICE ports are random and not exposed by docker. Did you came across this problem?

Thanks!

**Comment by jcrisp88** [comment]
Hey Ioannis,

Thanks for reaching out to me, and using my project 😁
Really sorry for the delayed reply, been a crazy busy week.

So, basically the webrtc protocol uses UDP and random ports. So, I have
opened all ports for UDP communication in the firewall rules.
[image: image.png]

Not sure what else I can suggest for this, this was the only issue I can
remember 🤔

Thanks,
John
